name: Java CI with Maven and Smooth Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21 for Spring Boot project
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      # Step 4: Stop any currently running instance of the app
      - name: Stop existing application
        run: |
          echo "Stopping any existing application running on port 8081..."
          pid=$(sudo lsof -t -i:8081 || echo "")
          if [ ! -z "$pid" ]; then
            echo "Killing process on port 8081 with PID $pid..."
            sudo kill -9 $pid
          else
            echo "No process running on port 8081."
          fi

      # Step 5: Deploy the Spring Boot application
      - name: Deploy Application
        run: |
          echo "Deploying the Spring Boot application..."
          nohup java -jar /home/ubuntu/actions-runner/_work/Group-2-Back-End/Group-2-Back-End/target/acccreation-0.0.1.jar > /home/ubuntu/app.log 2>&1 &
          echo "Application deployed successfully!"

      # Step 6: Verify the application is running
      - name: Verify Application
        run: |
          echo "Verifying application status..."
          sleep 10
          curl -f http://localhost:8081/actuator/health || exit 1
