name: Java CI/CD with Maven and EC2 Deployment

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21 for Maven
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build the application
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      # Step 4: Upload private key to SSH agent
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Step 5: Transfer JAR file to EC2 instance
      - name: Transfer JAR to EC2
        run: |
          scp -o StrictHostKeyChecking=no \
          target/acccreation-0.0.1.jar \
          ubuntu@16.171.194.30:/home/ubuntu/app.jar

      # Step 6: Start the application on EC2
      - name: Start Application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@16.171.194.30 << 'EOF'
          # Stop any running application
          if lsof -t -i:8081 >/dev/null; then
            echo "Stopping existing application..."
            sudo kill -9 $(lsof -t -i:8081)
          fi

          # Start the new application
          echo "Starting new application..."
          nohup java -jar /home/ubuntu/app.jar > /home/ubuntu/app.log 2>&1 &
          EOF

      # Step 7: Verify the application is running
      - name: Verify Application
        run: |
          sleep 60  # Increase sleep time to give the app more time to start
          curl -f http://16.171.194.30:8081/actuator/health || exit 1
      
